# Verwende ein Node.js-Image als Basis
FROM node:22

# Arbeitsverzeichnis setzen
WORKDIR /app

# Kopiere den gesamten Code ins Docker-Image
COPY ../ .

# Exponiere Port 3000 für Webpack DevServer
EXPOSE 3000

# Starte den Webpack-Dev-Server
CMD ["npm", "run", "dev"]